version: '3'

services:
  client:
    # stdin_open: true #For development live reload support
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    # volumes: # For development live reload support
    #   - /app/node_modules
    #   - ./client:/app
  worker:
    container_name: worker
    build:
      context: ./worker
      # dockerfile: Dockerfile.dev # For development
      dockerfile: Dockerfile.prod
    # volumes: # For development live reload support
    #   - /app/node_modules
    #   - ./worker:/app
    ports:
      - 4000:4000
    environment:
      - PORT=4000
  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile.dev # For development
      # dockerfile: Dockerfile.prod
    restart: always
    volumes: # For development live reload support
      - /app/node_modules
      - ./server:/app
    ports:
      - 5000:5000
    environment:
      - PORT=5000
  redis:
    container_name: redis
    image: 'redis:4-alpine'
    command: redis-server --requirepass 123456
    ports:
      - '6379:6379'
  mongo:
    container_name: mongo
    volumes:
      - ./data:/data/db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
