version: '3'

services:
  mongo:
    container_name: mongo
    volumes:
      - ./data:/data/db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
