apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: gkabitakis/server:v1.0.1
          env:
            - name: MONGO_HOST
              value: mongo-svc
            - name: MONGO_USER
              value: root
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-pass
                  key: MONGO_PASS
            - name: WORKER_HOST
              value: http://worker-svc:5001
            - name: REDIS_HOST
              value: redis-svc
            - name: REDIS_PORT
              value: '6379'
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: redis-pass
                  key: REDIS_PASS
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: server-svc
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 5000
      targetPort: 5000
